name: Start_Workflow

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch and Repository Info Files
        run: |
          echo "${{ inputs.branch }}" > branch.txt
          echo "${{ inputs.repository }}" > repository.txt

      - name: Upload Branch and Repository Info as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: branch-info
          path: |
            branch.txt
            repository.txt
