name: Ansible Lint

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: 'Repository name to perform ansible-lint'
      branch:
        required: true
        type: string
        description: 'Branch name to check out and push to'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: List Files to be Linted
        run: |
          echo "Listing all YAML files that will be linted, excluding '.github' folder:"
          find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

      - name: Run Ansible Lint
        run: ansible-lint

      - name: Merge 
        if: success()
        run: |
          git config user.name "piptest"
          git config user.email "emailpi@mail.com"
          git fetch origin
          git merge origin/main --no-ff --no-commit -X theirs --allow-unrelated-histories

      - name: Push to Branch
        if: success()
        run: |
          BRANCH_NAME=${{ github.event.inputs.branch }}
          echo "Pushing to branch: $BRANCH_NAME"

          git config user.name "piptest"
          git config user.email "emailpi@mail.com"
          
          # Check for changes
          git fetch origin
          git merge origin/$BRANCH_NAME --no-ff --no-commit -X theirs --allow-unrelated-histories

          # Only commit if there are changes
          if ! git diff --quiet
          then
            git commit -m "Merged branch $BRANCH_NAME into $BRANCH_NAME"
            git push https://${{ secrets.PAT_MAX }}@github.com/${{ github.event.inputs.repository }}/$BRANCH_NAME
          else
            echo "No changes to commit on branch $BRANCH_NAME."
          fi
