name: Ansible Lint

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: 'Repository name to push changes'

jobs:
  lint-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # or any specific version you need

    - name: Install Ansible Lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint

    - name: Run Ansible Lint
      run: ansible-lint

    - name: Push to Main-Production
      if: success()
      run: |
        git checkout -b main-production
        git push origin main-production
