name: Ansible Lint

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
        description: 'Repository name to perform ansible-lint'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # or any specific version you need
    - name: Install Ansible Lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint

    - name: List Files to be Linted
      run: |
        echo "Listing all YAML files that will be linted, excluding '.github' folder:"
        find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

    - name: Run Ansible Lint
      run: ansible-lint
