name: Ansible Lint

on:
  workflow_run:
    workflows: ["Start Workflow"]
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download Branch and Repository Info
        uses: actions/download-artifact@v2
        with:
          name: branch-info

      - name: Extract Branch and Repository Info
        run: |
          BRANCH_NAME=$(cat branch.txt)
          REPOSITORY=$(cat repository.txt)
          echo "Branch: $BRANCH_NAME, Repository: $REPOSITORY"

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: $REPOSITORY
          ref: $BRANCH_NAME

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint

      - name: List Files to be Linted
        run: |
          echo "Listing all YAML files that will be linted, excluding '.github' folder:"
          find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

      - name: Run Ansible Lint
        run: ansible-lint









# name: Ansible Lint

# on:
#   workflow_call:
#     inputs:
#       repository:
#         required: true
#         type: string
#         description: 'Repository name to perform ansible-lint'
#       branch:
#         required: true
#         type: string
#         description: 'Branch name to check out and push to'

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
#         with:
#           repository: ${{ inputs.repository }}
#           ref: ${{ inputs.branch }}

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.x'

#       - name: Install Ansible Lint
#         run: |
#           python -m pip install --upgrade pip
#           pip install ansible-lint

#       - name: List Files to be Linted
#         run: |
#           echo "Listing all YAML files that will be linted, excluding '.github' folder:"
#           find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

#       - name: Run Ansible Lint
#         run: ansible-lint

#       # - name: Push to Branch
#       #   if: success()
#       #   run: |
#       #     BRANCH_NAME=${{ inputs.branch }}
#       #     echo "Pushing to branch: $BRANCH_NAME"
#       #     git config user.name "piptest"
#       #     git config user.email "emailpi@mail.com"
          
#       #     git fetch origin
#       #     if [ -z "$BRANCH_NAME" ]; then
#       #       echo "Error: BRANCH_NAME is not set."
#       #       exit 1
#       #     fi
      
#       #     git merge origin/$BRANCH_NAME --no-ff --no-commit -X theirs --allow-unrelated-histories || { echo "Merge failed"; exit 1; }
      
#       #     if ! git diff --quiet; then
#       #       git commit -m "Merged branch $BRANCH_NAME"
#       #       git push https://${{ secrets.PAT_MAX }}@github.com/${{ inputs.repository }}/$BRANCH_NAME
#       #     else
#       #       echo "No changes to commit on branch $BRANCH_NAME."
#       #     fi
      
