name: Auto Merge PR

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        run: |
          gh pr merge ${{ inputs.pull_request_number }} --repo ${{ github.repository }} --squash
        env:
          GH_TOKEN: ${{ github.token  }}
