name: Auto Merge PR

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: Merge Pull Request from repo1
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --repo ${{ inputs.repository }} --squash
        env:
          GH_TOKEN: ${{ secrets.PAT_MAX }}
