name: Auto Merge PR

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number
      repository:  # Define repository as an input
        required: true
        type: string        
jobs:
  auto-merge-job:
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        run: |
          gh pr merge ${{ inputs.pull_request_number }} --repo ${{ github.repository }} --squash --auto
        env:
          GH_TOKEN: ${{ secrets.PAT_MAX  }}


  