name: Approve PR Workflow

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        run: |
          gh pr review --approve --repo ${{ github.repository }} ${{ inputs.pull_request_number }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
