name: Approve PR Workflow

on:
  workflow_call:
    inputs:
      pull_request_number:
        required: true
        type: number

jobs:
  approve-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        run: | # approve the pull request
          curl --request POST \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{inputs.pull_request_number }}/reviews \
          --header 'authorization: Bearer ${{ secrets.GH_TOKEN }}' \
          --header 'content-type: application/json' \
          -d '{"event":"APPROVE"}'