name: Combined Workflow

on:
  workflow_call:
    inputs:
      repository:  # Define repository as an input
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - name: Install Ansible Lint
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint

    - name: List Files to be Linted
      run: |
        echo "Listing all YAML files that will be linted, excluding '.github' folder:"
        find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

    - name: Run Ansible Lint
      run: ansible-lint

  push_to_branch:
    needs: ansible_lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.branch }}
          token: ${{ github.token  }}

      - name: Push to Branch
        if: success()
        run: |
          echo "Pushing to branch: ${{ github.event.inputs.branch }}"
          git config user.name "piptest"
          git config user.email "emailpi@mail.com"
          
          git fetch origin
          if [ -z "${{ github.event.inputs.branch }}" ]; then
            echo "Error: BRANCH_NAME is not set."
            exit 1
          fi
      
          git merge origin/${{ github.event.inputs.branch }} --no-ff --no-commit -X theirs --allow-unrelated-histories || { echo "Merge failed"; exit 1; }
      
          if ! git diff --quiet; then
            git commit -m "Merged branch ${{ github.event.inputs.branch }}"
            git push https://${{ secrets.PAT_MAX }}@github.com/${{ inputs.repository }}/${{ github.event.inputs.branch }}
          else
            echo "No changes to commit on branch ${{ github.event.inputs.branch }}."
          fi
