name: Combined CI/CD Workflow

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
permissions: write-all

jobs:
  print-environment-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print All Variables
        run: |
          echo "Printing all environment variables:"
          printenv  
  ansible_lint:
    if: ${{ github.event_name != 'pull_request' }}    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: List Files to be Linted
        run: |
          echo "Listing all YAML files that will be linted, excluding '.github' folder:"
          find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'
      - name: Run Ansible Lint
        uses: ansible/ansible-lint@v6.22.1
        with:
          args: --profile production --exclude .github/

  merge-on-success:
    runs-on: ubuntu-latest
    needs: ansible_lint
    if: ${{ github.event_name == 'pull_request' }}    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.pull_request_ref }}

      - name: Merge Pull Request
        run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" 
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/merge
