name: Combined Workflow

on:
  workflow_call:
    inputs:
      repository:  # Define repository as an input
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: List Files to be Linted
        run: |
          echo "Listing all YAML files that will be linted, excluding '.github' folder:"
          find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'

      - name: run-ansible-lint
        uses: ansible/ansible-lint@v6.22.1
        with:
          args: --profile production --exclude .github/