name: Combined Workflow

on:
  workflow_call:
    inputs:
      repository:  # Define repository as an input
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Ansible Lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint
      - name: List Files to be Linted
        run: |
          echo "Listing all YAML files that will be linted, excluding '.github' folder:"
          find . -name '*.yml' -or -name '*.yaml' | grep -v './.github/'
      - name: Run Ansible Lint
        run: ansible-lint

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run checks
        run: |
          # Add your checks here. For example:
          # npm install
          # npm test
      - name: Merge PR
        if: ${{ success() }}
        run: |
          git checkout master
          git merge --no-ff --no-edit ${{ github.event.pull_request.head.ref }}
          git push origin master
      - name: Close PR
        if: ${{ success() }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
