name: Combined CI/CD Workflow

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.branch }}

      # ... rest of the Ansible lint steps ...

  merge-on-success:
    runs-on: ubuntu-latest
    needs: ansible_lint
    if: ${{ github.event.pull_request.merged == false }}
    steps:
      - name: Merge PR
        if: success()
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

  close-on-failure:
    runs-on: ubuntu-latest
    needs: ansible_lint
    if: ${{ github.event.pull_request.merged == false }}
    steps:
      - name: Close PR
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: "closed"
            })
