name: Push to Branch

on:
  workflow_run:
    workflows: [Ansible_Lint]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Branch and Repository Info
        uses: actions/download-artifact@v2
        with:
          name: branch-info

      - name: Extract Branch and Repository Info
        run: |
          BRANCH_NAME=$(cat branch.txt)
          REPOSITORY=$(cat repository.txt)
          echo "Branch: $BRANCH_NAME, Repository: $REPOSITORY"

      - name: Push to Branch
        if: success()
        run: |
          echo "Pushing to branch: $BRANCH_NAME"
          git config user.name "piptest"
          git config user.email "emailpi@mail.com"
          
          git fetch origin
          if [ -z "$BRANCH_NAME" ]; then
            echo "Error: BRANCH_NAME is not set."
            exit 1
          fi
      
          git merge origin/$BRANCH_NAME --no-ff --no-commit -X theirs --allow-unrelated-histories || { echo "Merge failed"; exit 1; }
      
          if ! git diff --quiet; then
            git commit -m "Merged branch $BRANCH_NAME"
            git push https://${{ secrets.PAT_MAX }}@github.com/${{ inputs.repository }}/$BRANCH_NAME
          else
            echo "No changes to commit on branch $BRANCH_NAME."
          fi

# name: Push to Branch

# on:
#     workflow_run:
#       workflows: ["Ansible Lint"]
#       types:
#         - completed

# jobs:
#   push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Push to Branch
#         if: success()
#         run: |
#           BRANCH_NAME=${{ inputs.branch }}
#           echo "Pushing to branch: $BRANCH_NAME"
#           git config user.name "piptest"
#           git config user.email "emailpi@mail.com"
          
#           git fetch origin
#           if [ -z "$BRANCH_NAME" ]; then
#             echo "Error: BRANCH_NAME is not set."
#             exit 1
#           fi
      
#           git merge origin/$BRANCH_NAME --no-ff --no-commit -X theirs --allow-unrelated-histories || { echo "Merge failed"; exit 1; }
      
#           if ! git diff --quiet; then
#             git commit -m "Merged branch $BRANCH_NAME"
#             git push https://${{ secrets.PAT_MAX }}@github.com/${{ inputs.repository }}/$BRANCH_NAME
#           else
#             echo "No changes to commit on branch $BRANCH_NAME."
#           fi
      
          