name: Start Workflow

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
        description: 'Repository name for subsequent workflows'
      branch:
        required: true
        type: string
        description: 'Branch name for subsequent workflows'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch and Repository Info Files
        run: |
          echo "${{ github.event.inputs.branch }}" > branch.txt
          echo "${{ github.event.inputs.repository }}" > repository.txt

      - name: Upload Branch and Repository Info as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: branch-info
          path: |
            branch.txt
            repository.txt
